# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Geonho You / Marco You
title: Graduate Student in Economics at PSE and ENPC
email: gunhoqw20@gmail.com
website: www.github.com/MarcoYou

# Social links
# twitter_username: -
github_username: MarcoYou
# dribbble_username: jekyll
facebook_username: marco.you.5494
# flickr_username: jekyll
instagram_username: MRCinanutshell
linkedin_username: geonho-marco-you-0090b9150
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/CV Pic-white.jpeg
about_content: | # this will include new lines to allow paragraphs

  Hello, welcome to my resume site.
  My name is Marco and I'm a graduate student in economics from South Korea living in Paris since 2012.
  
  <br/>
  
  I am most skilled in: <mark>Statistics</mark> and <mark>Making Kimchi</mark>!

# Projects Section
projects_title: Projects & Papers

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Interests
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in economics and finance, some of my other interests are:
   - Investment: I have been investing in numerous stocks and ETFs. It taught me to understand different ratios and momentum of stocks.
   - Technology: I visited at IBM-Korea in 2018 and conducted an interview with the Sales Manager Mr.Park, about IBMâ€™s Artificial Intelligence Watson
   - Sport: I lost 30kg 100kg between 2016 and 2017! It was a huge challenge.
   - [Making Kimchi](https://www.youtube.com/watch?v=jm5wWji2Dds)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag


